### PR TITLE
Fixed TopArtists data display issue

### LINKED ISSUE #7: ITERATION ONE:  INITIAL SET UP, DISPLAYS, SONGS; DEV TASKS
- [x] Build Modular File Structure For Envisioned Components
- [x] Fix file paths for connectivity 
- [x] Create Utils file: 
     - create api calls file
     - create utils file for cleaner functions
- [x] Connect API
- [x] Build basic class component structure for display
     * App
          * Header
          * Nav
          * Main Display
               * Top Artists
               * Top Tracks
          *  `<Switch/>`
                *  Artist Info
                *  Artist Track       
- [x] Build basic function component structure for display

### PR DESCRIPTION
**Pull request by pcmueller**
### Is this a fix or a feature?
- Fix

### What is the change or fix?
- Added conditional rendering to give the DOM a "Page Loading" display while API data is being fetched.  We were getting browser errors because it was rendering the "TopArtists" component before the state update.
- Also, I moved all of our async functionality inside of the apiCalls.js functions, and nested those functions as methods inside a parent apiCalls() function.  Confusing wording but you'll get it when you see it.  All of this is probably unnecessary since our bug wasn't related to that - we can definitely revert back to the way Bryan had it structured, I just couldn't remember the exact syntax.

### How should this be tested?
- Run in browser, and build out Cypress testing.

### CODE REVIEW

File: src/components/App/App.js [hunk 1]
```diff
@@ -12,55 +12,67 @@ class App extends Component {
...
  showTopTracks = async () => {
-     getTopTracks()
-        .then(data => {
-          this.setState({topTracks: data.topTracks})
-        })
-        .catch(error => {
-          this.setState({error: error.message})
-        })
-    console.log(this.state.topTracks)
+     apiCalls.getTopTracks()
```
Comment (bhohnco) [inline src/components/App/App.js:35]: nice work getting this to fire

File: src/components/TopArtists/TopArtists.js [hunk 2]
```diff
@@ -1,33 +1,32 @@
...
+          <li className='top-artist'>{artistNames[0]}</li>
+          <li className='top-artist'>{artistNames[1]}</li>
+          <li className='top-artist'>{artistNames[2]}</li>
+          <li className='top-artist'>{artistNames[3]}</li>
+          <li className='top-artist'>{artistNames[4]}</li>
+          <li className='top-artist'>{artistNames[5]}</li>
+          <li className='top-artist'>{artistNames[6]}</li>
+          <li className='top-artist'>{artistNames[7]}</li>
+          <li className='top-artist'>{artistNames[8]}</li>
+          <li className='top-artist'>{artistNames[9]}1</li>
```
Comment (bhohnco) [inline src/components/TopArtists/TopArtists.js:25]: Looking good!

File: src/utilities/apiCalls.js [hunk 3]
```diff
@@ -7,29 +7,25 @@ const artistInfoUrl = "http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&a
...
-      })
+const apiCalls = {
+
+  async getTopArtists() {
+    const response = await fetch(topArtistByCountryUrl)
+    const data = await response.json();
+    return data;
+  },
+  
+  async getTopTracks() {
```
Comment (bhohnco) [inline src/utilities/apiCalls.js:19]: good call adjusting this

**Review by bhohnco — APPROVED** [review]
