### PR TITLE
Fix/dynamic artist page routing

### LINKED ISSUE #9: ITERATION TWO: DISPLAY SINGLE ARTIST
- [x] NONE OF THE OTHER ARTISTS ARE ON DISPLAY
- [x] ON CLICK A SINGLE ARTISTS DETAILS ARE DISPLAY
     * NAME
     * SUMMARY
     * BIO
     * TOP TRACKS
          * (NEW API CALL) DISPLAY SINGLE ARTIST 
          TOP TRACKS      
- [ ] IMPLEMENT ROUTER FOR CONDITIONS OF RENDER
- [x] Even WITH ARTIST DETAILS DISPLAYING USER SHOULD BE ABLE TO NAVIGATE BACK TO THE MAIN PAGE VIEW
- [ ] CYRPRESS TEST FOR SINGLE ARTIST VIEW

### LINKED ISSUE #33: ROUTER
- [x] Implement main page switching (once "ArtistInfo" functionality has been built out)
- [x] Connect "home" button functionality
- [x] Connect "random location" button functionality
- [ ] Connect "dropdown menu" functionality
- [ ] Connect "search bar" functionality

### PR DESCRIPTION
**Pull request by pcmueller**
### Is this a fix or a feature?
- Fix, with some CSS features as well.

### What is the change or fix?
- Fixed the <ArtistInfo> route so that we use `match.params.id` (the artist name in the URL) to dynamically fetch different artist info API objects, do be rendered on the AristInfo page display.  
- Refactored the "artist name" HTML element (in the ArtistInfo display) so that it's now a hyperlink that can be clicked to take the user to that artist's Last.fm page.
- Same for each TopTrack <li> on the home page view - individual track names can be clicked to reroute to that song's Last.fm page.
- Restyled the Header's nav buttons ("Randomize Location" and "Return Home") so that they better fit with our UI, including a hover effect to communicate that they can be clicked.
- Removed the "artist summary" element from ArtistInfo, since it's just the first paragraph of the longer "artist bio" element.  
- Refactored the "artist info" container styling so that when you scroll down to view more text, the parent container / entire page remains fixed in it's position.

### How should this be tested?
- Display in browser.
- We should now be able to implement Cypress testing for all ArtistInfo components and functionality, now that it loads and renders the correct data.

### Linked Issues:
- #9 #33

### CODE REVIEW

File: src/components/Header/Header.js [hunk 1]
```diff
@@ -9,10 +9,10 @@ const Header = () => {
       <h1 className='glow'>W o r m h o l e</h1>
       <nav>
         <Link exact to='/'>
-          <button className='random-location'>Randomize Location</button>
+          <button className='nav-btn'>Randomize Location</button>
         </Link>
         <Link exact to='/'>
-          <button className='go-home'>Return Home</button>
+          <button className='nav-btn'>Return Home</button>
```
Comment (battan40) [inline src/components/Header/Header.js:15]: i will adjust these styling names to fit the cypress tests when i pull down; I will maintain your styles.

**Review by battan40 — APPROVED** [review]
